- name: template the cgi
  sudo: true
  template: >
    src=cgi.cfg
    dest=/usr/local/nagios/etc/cgi.cfg
    owner=nagios
    group=nagios
    mode=755
  tags:
      - etc
        
- name: template the nagios.cfg
  sudo: true
  template: >
    src=nagios.cfg
    dest=/usr/local/nagios/etc/nagios.cfg
    owner=nagios
    group=nagios
    mode=755
  tags:
      - etc

- name: template the files
  sudo: true
  template: >
    src="{{ item }}"
    dest="/usr/local/nagios/etc/objects/{{ item }}"
    owner=nagios
    group=nagios
    mode=755
  with_items:
      - commands.cfg
      - localhost.cfg
      - prd.cfg
  tags:
      - etc

- name: restart nagios
  sudo: true
  service: name=nagios4 state=restarted
  notify: restart apache
  tags:
      - etc
